### ISSUE TITLE
fetchCredential ENS Error

### ISSUE THREAD

**Issue by jreedy-riis** [energywebfoundation/ew-credentials#71]
# Description
Hello, I have been trying to fetch credentials through the iam-client-lib with `claimsService.fetchCredentials` or `claimsService.resolveCredentialsAndVerify`. However, when given certain (maybe old?) DID, this function throws an ENS Undefined Error. I have also created brand new wallet accounts with only a couple of roles (all made on latest version of iam-client-lib) and the function worked fine, however, today the function is now throwing the same error for my new addresses. I believe the only thing that I did to my DID document was create a self-signed claim. 

# Code
https://github.com/energywebfoundation/ew-credentials/blob/19108ef86410e85aad71bc47d44ddf202ced716f/packages/vc-verification/src/resolver/Ipfs-credential-resolver.ts#L106-L116

I believe in some cases when the `jwt?.payload?.claimData.claimType` is undefined, `utils.namehash` still tries to parse it, causing the error. I removed the `utils.namehash` check in my node-module and the function worked fine.

# Error
invalid ENS name; not a string (argument="name", value=undefined, code=INVALID_ARGUMENT, version=hash/5.7.0).

**Comment by jrhender** [comment]
Thanks, good find @jreedy-riis . We will investigate and fix.

**Comment by JGiter** [comment]
@jreedy-riis This should be fixed in latest iam-lib. Could you check that?

**Comment by jreedy-riis** [comment]
Hello! It looks like it is fixed, thank you!
